Added Shopping Cart Analytics Stack
airbytehq/quickstarts pull request #82
Opened 2023-11-03 13:51 UTC by bishalbera

Closes #24

2023-11-06 14:56 UTC, ThaliaBarrera requested changes

2023-11-07 00:09 UTC, bishalbera commented on shopping_cart_analytics_shopify/orchestration/orchestration/assets.py
> +airbyte_assets = load_assets_from_airbyte_instance(airbyte_instance,)
ohk got it. May be that's why Airbyte assets were named like default

2023-11-07 00:25 UTC, bishalbera commented on shopping_cart_analytics_shopify/orchestration/orchestration/assets.py
> +airbyte_assets = load_assets_from_airbyte_instance(airbyte_instance,)
@ThaliaBarrera Done check again please :)

2023-11-07 13:46 UTC, ThaliaBarrera approved these changes

2023-11-07 13:46 UTC, merged